DROP DATABASE IF EXISTS battledb;
CREATE DATABASE IF NOT EXISTS battledb;   
USE battledb;

DROP TABLE IF EXISTS Address;
CREATE TABLE Address(
  id BIGINT AUTO_INCREMENT NOT NULL,
  district VARCHAR(45) NOT NULL,
  street VARCHAR(45) NOT NULL,
  houseNumber VARCHAR(45) NOT NULL,
  apartment VARCHAR(45) NOT NULL,
  PRIMARY KEY(id)
)ENGINE = InnoDB CHARACTER SET=UTF8;

DROP TABLE IF EXISTS Role;
CREATE TABLE Role(
  id BIGINT AUTO_INCREMENT NOT NULL,
  name VARCHAR(45) NOT NULL,
  PRIMARY KEY(id)
)ENGINE = InnoDB CHARACTER SET=UTF8;

DROP TABLE IF EXISTS User;
CREATE TABLE User(
  id BIGINT AUTO_INCREMENT NOT NULL,
  name VARCHAR(45) NOT NULL,
  surname VARCHAR(45) NOT NULL,
  login VARCHAR(45) NOT NULL,
  password VARCHAR(45) NOT NULL,
  photoPath VARCHAR(45) NOT NULL,
  email VARCHAR(45) NOT NULL,
  address_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  commentAble TINYINT(1) NOT NULL DEFAULT 0,
  active TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY(id),
  FOREIGN KEY (address_id) REFERENCES Address(id),
  FOREIGN KEY (role_id) REFERENCES Role(id)
)ENGINE = InnoDB CHARACTER SET=UTF8;

DROP TABLE IF EXISTS Competition;
CREATE TABLE Competition(
  id BIGINT AUTO_INCREMENT NOT NULL,
  name VARCHAR(45) NOT NULL,
  description VARCHAR(25500) NOT NULL,
  dateStart DATE,
  dateEnd DATE,
  registerDeadline DATE,
  winner_id BIGINT NOT NULL,
  PRIMARY KEY(id),
  FOREIGN KEY (winner_id) REFERENCES User(id)
)ENGINE = InnoDB CHARACTER SET=UTF8;

DROP TABLE IF EXISTS Project;
CREATE TABLE Project(
  id BIGINT AUTO_INCREMENT NOT NULL,
  name VARCHAR(45) NOT NULL,
  description VARCHAR(25500) NOT NULL,
  creationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  user_id BIGINT NOT NULL,
  competition_id BIGINT NOT NULL,
  approved TINYINT(1) DEFAULT 0,
  PRIMARY KEY(id),
  FOREIGN KEY (user_id) REFERENCES User(id),
  FOREIGN KEY (competition_id) REFERENCES Competition(id)
)ENGINE = InnoDB CHARACTER SET=UTF8;

DROP TABLE IF EXISTS Photo;
CREATE TABLE Photo(
  id BIGINT AUTO_INCREMENT NOT NULL,
  path VARCHAR(45) NOT NULL,
  loadDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  description VARCHAR(25500),
  project_id BIGINT NOT NULL,
  PRIMARY KEY(id),
  FOREIGN KEY (project_id) REFERENCES Project(id)
)ENGINE = InnoDB CHARACTER SET=UTF8;

DROP TABLE IF EXISTS Comment;
CREATE TABLE Comment(
  id BIGINT AUTO_INCREMENT NOT NULL,
  commentText VARCHAR(45) NOT NULL,
  commentDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  user_id BIGINT NOT NULL,
  project_id BIGINT NOT NULL,
  photo_id BIGINT,
  PRIMARY KEY(id),
  FOREIGN KEY (user_id) REFERENCES User(id),
  FOREIGN KEY (project_id) REFERENCES Project(id),
  FOREIGN KEY (photo_id) REFERENCES Photo(id)
)ENGINE = InnoDB CHARACTER SET=UTF8;

DROP TABLE IF EXISTS Voice;
CREATE TABLE Voice(
  id BIGINT AUTO_INCREMENT NOT NULL,
  level INT NOT NULL,
  voiceDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  user_id BIGINT NOT NULL,
  project_id BIGINT NOT NULL,
  PRIMARY KEY(id),
  FOREIGN KEY (user_id) REFERENCES User(id),
  FOREIGN KEY (project_id) REFERENCES Project(id)
)ENGINE = InnoDB CHARACTER SET=UTF8;


